import AppKit
import SwiftUI
import UniformTypeIdentifiers

// MARK: - Clipboard history

struct Clip: Identifiable, Codable, Equatable {
    enum Kind: String, Codable { case text, link, image }
    var id = UUID()
    var kind: Kind
    var text: String?
    var imagePath: String?
    var date = Date()
    var app: String?
}

/// Local clipboard shelf: text, links and images, newest first. Polls the
/// pasteboard's change count (the only API macOS offers) and skips anything a
/// password manager marks concealed or transient — nspasteboard.org's
/// convention, honoured by 1Password, Bitwarden, KeePassXC and friends.
@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var clips: [Clip] = []
    private var lastChange = NSPasteboard.general.changeCount
    private var ignoreChange = -1
    private var suppressUntil = Date.distantPast
    private var timer: Timer?
    private let indexPath = opennotchDir("clips") + "/index.json"
    private let limit = 150

    private static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    ]

    func start() {
        if let data = try? Data(contentsOf: URL(fileURLWithPath: indexPath)),
           let saved = try? JSONDecoder().decode([Clip].self, from: data) {
            clips = saved
        }
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        if pb.changeCount == ignoreChange || Date() < suppressUntil { return }
        let types = Set((pb.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skipTypes) else { return }
        let app = NSWorkspace.shared.frontmostApplication?.localizedName

        // Skip enormous images (a 40-megapixel paste) rather than stall the main thread.
        let imageBytes = (pb.data(forType: .png) ?? pb.data(forType: .tiff))?.count ?? 0
        if imageBytes > 30_000_000 { return }
        if let img = NSImage(pasteboard: pb), types.contains(NSPasteboard.PasteboardType.png.rawValue)
            || types.contains(NSPasteboard.PasteboardType.tiff.rawValue),
           !types.contains(NSPasteboard.PasteboardType.fileURL.rawValue) {
            let clip = Clip(kind: .image, imagePath: nil, app: app)
            let path = opennotchDir("clips") + "/\(clip.id.uuidString).png"
            if let tiff = img.tiffRepresentation, let rep = NSBitmapImageRep(data: tiff),
               let png = rep.representation(using: .png, properties: [:]) {
                try? png.write(to: URL(fileURLWithPath: path))
                var c = clip
                c.imagePath = path
                insert(c)
            }
            return
        }
        if let s = pb.string(forType: .string), !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let isLink = s.range(of: #"^\s*https?://\S+\s*$"#, options: .regularExpression) != nil
            insert(Clip(kind: isLink ? .link : .text, text: String(s.prefix(100_000)), app: app))
        }
    }

    /// Don't record clipboard changes for a moment — writing tools briefly use
    /// the clipboard to paste, and that isn't something you copied.
    func suppressNextChange(for seconds: TimeInterval = 1.5) {
        suppressUntil = Date().addingTimeInterval(seconds)
    }

    func addImage(path: String) {
        insert(Clip(kind: .image, imagePath: path, app: "OpenNotch"))
    }

    private func insert(_ c: Clip) {
        if c.kind != .image, let i = clips.firstIndex(where: { $0.text == c.text }) {
            clips.remove(at: i)                              // re-copied: move to top
        }
        clips.insert(c, at: 0)
        if clips.count > limit {
            for old in clips[limit...] { if let p = old.imagePath { try? FileManager.default.removeItem(atPath: p) } }
            clips = Array(clips.prefix(limit))
        }
        save()
    }

    func copy(_ c: Clip) {
        let pb = NSPasteboard.general
        pb.clearContents()
        if let p = c.imagePath, let img = NSImage(contentsOfFile: p) {
            pb.writeObjects([img])
        } else if let t = c.text {
            pb.setString(t, forType: .string)
        }
        ignoreChange = pb.changeCount                        // don't re-record our own copy
        if let i = clips.firstIndex(of: c) { clips.move(fromOffsets: IndexSet(integer: i), toOffset: 0); save() }
    }

    func delete(_ c: Clip) {
        if let p = c.imagePath { try? FileManager.default.removeItem(atPath: p) }
        clips.removeAll { $0.id == c.id }
        save()
    }

    func clear() {
        clips.forEach { if let p = $0.imagePath { try? FileManager.default.removeItem(atPath: p) } }
        clips = []
        save()
    }

    private func save() {
        if let data = try? JSONEncoder().encode(clips) { try? data.write(to: URL(fileURLWithPath: indexPath)) }
    }
}

struct ClipboardView: View {
    @ObservedObject var store: ClipboardStore
    @ObservedObject var backend: Backend
    @ObservedObject var hub: Hub
    @State private var filter = "All"
    @State private var query = ""
    @State private var copiedID: UUID?

    private var shown: [Clip] {
        store.clips.filter { c in
            switch filter {
            case "Text": return c.kind == .text
            case "Links": return c.kind == .link
            case "Images": return c.kind == .image
            default: return true
            }
        }.filter { c in query.isEmpty || (c.text ?? "").localizedCaseInsensitiveContains(query) }
    }

    var body: some View {
        VStack(spacing: 0) {
            ModuleHeader(title: "Clipboard", subtitle: "\(store.clips.count) items · stays on this Mac") {
                Button("Clear") { store.clear() }.buttonStyle(.plain).font(.system(size: 11)).foregroundStyle(Theme.secondary)
            }
            HStack(spacing: 6) {
                ForEach(["All", "Text", "Links", "Images"], id: \.self) { f in
                    Chip(label: f, selected: filter == f) { filter = f }
                }
                Spacer()
                SearchField(text: $query, placeholder: "Filter")
                    .frame(width: 150)
            }
            .padding(.horizontal, 18).padding(.bottom, 8)
            if shown.isEmpty {
                EmptyHint(icon: "doc.on.clipboard", text: "Copy anything — text, links, images, screenshots — and it lands here.")
            } else {
                ScrollView {
                    LazyVStack(spacing: 6) {
                        ForEach(shown) { c in row(c) }
                    }
                    .padding(.horizontal, 14).padding(.bottom, 14)
                }
            }
        }
    }

    @ViewBuilder
    private func row(_ c: Clip) -> some View {
        HStack(spacing: 10) {
            if c.kind == .image, let p = c.imagePath, let img = NSImage(contentsOfFile: p) {
                Image(nsImage: img).resizable().aspectRatio(contentMode: .fill)
                    .frame(width: 64, height: 44).clipShape(RoundedRectangle(cornerRadius: 6))
            } else {
                Image(systemName: c.kind == .link ? "link" : "text.alignleft")
                    .font(.system(size: 12)).foregroundStyle(Theme.secondary).frame(width: 22)
            }
            VStack(alignment: .leading, spacing: 3) {
                Text(c.kind == .image ? "Image" : (c.text ?? ""))
                    .font(.system(size: 12, design: c.kind == .link ? .monospaced : .default))
                    .lineLimit(2).foregroundStyle(.white.opacity(0.9))
                Text([c.app, relativeTime(c.date)].compactMap { $0 }.joined(separator: " · "))
                    .font(.system(size: 10)).foregroundStyle(Theme.tertiary)
            }
            Spacer(minLength: 0)
            if copiedID == c.id {
                Text("Copied").font(.system(size: 10, weight: .semibold)).foregroundStyle(.green)
            }
        }
        .padding(9)
        .background(RoundedRectangle(cornerRadius: 10).fill(.white.opacity(0.045)))
        .contentShape(RoundedRectangle(cornerRadius: 10))
        .onTapGesture {
            store.copy(c)
            copiedID = c.id
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.2) { if copiedID == c.id { copiedID = nil } }
        }
        .onDrag {
            if let p = c.imagePath { return NSItemProvider(contentsOf: URL(fileURLWithPath: p)) ?? NSItemProvider() }
            return NSItemProvider(object: (c.text ?? "") as NSString)
        }
        .contextMenu {
            Button("Copy") { store.copy(c) }
            Button("Ask Ledge about this") {
                if let p = c.imagePath { backend.attach(Attachment(kind: .screenshot, value: p)) }
                else if let t = c.text { backend.attach(Attachment(kind: .clipboard, value: t)) }
                hub.module = .chat
            }
            Divider()
            Button("Delete") { store.delete(c) }
        }
    }
}

struct SearchField: View {
    @Binding var text: String
    var placeholder: String
    var onSubmit: () -> Void = {}

    var body: some View {
        HStack(spacing: 6) {
            Image(systemName: "magnifyingglass").font(.system(size: 10)).foregroundStyle(Theme.tertiary)
            TextField(placeholder, text: $text).textFieldStyle(.plain).font(.system(size: 12)).onSubmit(onSubmit)
            if !text.isEmpty {
                Button { text = "" } label: { Image(systemName: "xmark.circle.fill").font(.system(size: 10)) }
                    .buttonStyle(.plain).foregroundStyle(Theme.tertiary)
            }
        }
        .padding(.horizontal, 9).padding(.vertical, 5)
        .background(Capsule().fill(.white.opacity(0.07)))
    }
}

// MARK: - File shelf

struct ShelfItem: Identifiable, Codable, Equatable {
    var id = UUID()
    var path: String
    var added = Date()
}

/// Files parked in the notch. References only — the originals are never
/// copied or moved; dragging out hands the other app the original URL.
@MainActor
final class ShelfStore: ObservableObject {
    @Published private(set) var items: [ShelfItem] = []
    private let path = opennotchDir("") + "/shelf.json"

    init() {
        if let data = try? Data(contentsOf: URL(fileURLWithPath: path)),
           let saved = try? JSONDecoder().decode([ShelfItem].self, from: data) {
            items = saved
        }
    }

    func add(_ urls: [URL]) {
        for u in urls where !items.contains(where: { $0.path == u.path }) {
            items.insert(ShelfItem(path: u.path), at: 0)
        }
        save()
    }

    func remove(_ i: ShelfItem) { items.removeAll { $0.id == i.id }; save() }
    func clear() { items = []; save() }

    private func save() {
        if let data = try? JSONEncoder().encode(items) { try? data.write(to: URL(fileURLWithPath: path)) }
    }
}

struct ShelfView: View {
    @ObservedObject var store: ShelfStore
    @ObservedObject var backend: Backend
    @ObservedObject var hub: Hub
    @State private var targeted = false

    var body: some View {
        VStack(spacing: 0) {
            ModuleHeader(title: "Shelf", subtitle: "Drop files here, drag them out anywhere. Originals stay put.") {
                if !store.items.isEmpty {
                    Button("Clear") { store.clear() }.buttonStyle(.plain).font(.system(size: 11)).foregroundStyle(Theme.secondary)
                }
            }
            if store.items.isEmpty {
                EmptyHint(icon: "tray.and.arrow.down", text: "Drag files onto the notch and choose “Keep on Shelf”,\nor drop them right here.")
            } else {
                ScrollView {
                    LazyVGrid(columns: Array(repeating: GridItem(.flexible(), spacing: 10), count: 5), spacing: 12) {
                        ForEach(store.items) { item in tile(item) }
                    }
                    .padding(14)
                }
            }
        }
        .background(RoundedRectangle(cornerRadius: 14).fill(targeted ? Color.white.opacity(0.05) : .clear).padding(8))
        .onDrop(of: [.fileURL], isTargeted: $targeted) { providers in
            loadURLs(providers) { store.add($0) }
            return true
        }
    }

    private func tile(_ item: ShelfItem) -> some View {
        let exists = FileManager.default.fileExists(atPath: item.path)
        return VStack(spacing: 6) {
            appIcon(forPath: item.path, size: 44).resizable().frame(width: 44, height: 44)
            Text((item.path as NSString).lastPathComponent)
                .font(.system(size: 10.5)).lineLimit(2).multilineTextAlignment(.center)
                .foregroundStyle(exists ? .white.opacity(0.85) : .red.opacity(0.7))
        }
        .frame(maxWidth: .infinity)
        .padding(8)
        .background(RoundedRectangle(cornerRadius: 10).fill(.white.opacity(0.04)))
        .opacity(exists ? 1 : 0.5)
        .onDrag { NSItemProvider(contentsOf: URL(fileURLWithPath: item.path)) ?? NSItemProvider() }
        .onTapGesture(count: 2) { NSWorkspace.shared.open(URL(fileURLWithPath: item.path)) }
        .contextMenu {
            Button("Open") { NSWorkspace.shared.open(URL(fileURLWithPath: item.path)) }
            Button("Show in Finder") { NSWorkspace.shared.activateFileViewerSelecting([URL(fileURLWithPath: item.path)]) }
            Button("Ask Ledge about it") {
                backend.attach(Attachment(kind: .file, value: item.path))
                hub.module = .chat
            }
            Divider()
            Button("Remove from shelf") { store.remove(item) }
        }
        .help(item.path)
    }
}

// MARK: - Quick notes

/// A scratchpad that saves every edit (debounced) to ~/Library/Application Support/OpenNotch/notes.md.
@MainActor
final class NotesStore: ObservableObject {
    @Published var text: String = "" { didSet { scheduleSave() } }
    @Published private(set) var savedAt: Date?
    private let path = opennotchDir("") + "/notes.md"
    private var pending: DispatchWorkItem?

    init() {
        text = (try? String(contentsOfFile: path, encoding: .utf8)) ?? ""
    }

    /// Write now (on quit) — the debounced save might not have fired yet.
    func flush() {
        pending?.cancel()
        try? text.write(toFile: path, atomically: true, encoding: .utf8)
    }

    private func scheduleSave() {
        pending?.cancel()
        let snapshot = text
        let work = DispatchWorkItem { [weak self] in
            guard let self else { return }
            try? snapshot.write(toFile: self.path, atomically: true, encoding: .utf8)
            Task { @MainActor in self.savedAt = Date() }
        }
        pending = work
        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + 0.4, execute: work)
    }
}

struct NotesView: View {
    @ObservedObject var store: NotesStore
    @ObservedObject var backend: Backend
    @ObservedObject var notch: NotchController
    @ObservedObject var hub: Hub
    @FocusState private var focused: Bool

    var body: some View {
        VStack(spacing: 0) {
            ModuleHeader(title: "Notes", subtitle: store.savedAt.map { "Saved \(relativeTime($0))" } ?? "Saves as you type") {
                HStack(spacing: 8) {
                    Button { copyToClipboard(store.text) } label: { Image(systemName: "doc.on.doc") }
                        .buttonStyle(.plain).foregroundStyle(Theme.secondary).help("Copy all")
                    Button {
                        backend.attach(Attachment(kind: .clipboard, value: store.text))
                        backend.send("Tidy up these notes: fix typos, group related points, and turn any to-dos into a checklist.")
                        hub.module = .chat
                    } label: { Label("Tidy with Ledge", systemImage: "sparkles").font(.system(size: 11)) }
                        .buttonStyle(.plain).foregroundStyle(Theme.secondary)
                        .disabled(store.text.isEmpty)
                }
            }
            TextEditor(text: $store.text)
                .font(.system(size: 13))
                .scrollContentBackground(.hidden)
                .focused($focused)
                .padding(10)
                .background(RoundedRectangle(cornerRadius: 12).fill(.white.opacity(0.04)))
                .padding(.horizontal, 14).padding(.bottom, 8)
            HStack {
                Text("\(store.text.split { $0 == " " || $0 == "\n" }.count) words")
                Spacer()
                Text("~/Library/Application Support/OpenNotch/notes.md")
            }
            .font(.system(size: 10)).foregroundStyle(Theme.tertiary)
            .padding(.horizontal, 18).padding(.bottom, 12)
        }
        .onChange(of: focused) { f in if f { notch.pinned = true } }     // stays open while you type
        .onAppear { DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) { focused = true } }
    }
}

// MARK: - File search (Spotlight)

struct FoundFile: Identifiable, Equatable {
    let id = UUID()
    let path: String
    let modified: Date?
}

/// Spotlight search by name *and* contents, the same index `mdfind` uses.
@MainActor
final class FileSearch: ObservableObject {
    @Published var query = ""
    @Published var contents = true
    @Published var scope = "Home"
    @Published private(set) var results: [FoundFile] = []
    @Published private(set) var searching = false
    /// Shown instead of results while waiting for / after refusing folder access.
    @Published private(set) var notice: String?
    /// Called before a folder access that may pop a macOS consent dialog
    /// (rule §5.3: the notch must get out of the dialog's way).
    var willPrompt: ((String) -> Void)?
    private var mdq: NSMetadataQuery?
    private var observer: NSObjectProtocol?
    private var readable: Set<String> = []   // folders already proven readable
    private var generation = 0

    func run() {
        mdq?.stop()
        if let observer { NotificationCenter.default.removeObserver(observer) }
        generation += 1
        let q = query.trimmingCharacters(in: .whitespaces)
        guard q.count >= 2 else { results = []; notice = nil; searching = false; return }
        let home = NSHomeDirectory()
        let dir = scope == "Home" ? home : "\(home)/\(scope)"
        if scope == "Home" || readable.contains(dir) {
            notice = nil
            start(q, dir)
            return
        }
        // Documents / Downloads / Desktop are TCC-protected. The first touch
        // (Spotlight resolves the scope with open()) blocks until the user
        // answers a consent dialog — on the main thread that froze the whole
        // notch (2026-09-30). Touch the folder on a background queue instead
        // and start the query only once access is known.
        let gen = generation, name = scope
        searching = true
        results = []
        notice = "Waiting for access to \(name) — answer the macOS dialog."
        // Already granted → the probe returns in milliseconds; only step the
        // notch aside if it's still waiting (i.e. a dialog is up).
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            MainActor.assumeIsolated {
                if gen == self.generation, self.notice != nil, self.searching {
                    self.willPrompt?("OpenNotch to read your \(name) folder")
                }
            }
        }
        DispatchQueue.global(qos: .userInitiated).async { @Sendable in
            let ok = (try? FileManager.default.contentsOfDirectory(atPath: dir)) != nil
            DispatchQueue.main.async {
                MainActor.assumeIsolated {
                    guard gen == self.generation else { return }   // superseded
                    if ok {
                        self.readable.insert(dir)
                        self.notice = nil
                        self.start(q, dir)
                    } else {
                        self.searching = false
                        self.notice = "OpenNotch can't read \(name). Allow it in System Settings › Privacy & Security › Files and Folders, or search Home."
                    }
                }
            }
        }
    }

    private func start(_ q: String, _ dir: String) {
        let m = NSMetadataQuery()
        let escaped = q.replacingOccurrences(of: "\"", with: "")
        let name = NSPredicate(format: "%K CONTAINS[cd] %@", NSMetadataItemFSNameKey, escaped)
        m.predicate = contents
            ? NSCompoundPredicate(orPredicateWithSubpredicates: [
                name, NSPredicate(format: "kMDItemTextContent CONTAINS[cd] %@", escaped)])
            : name
        m.searchScopes = [dir]
        m.sortDescriptors = [NSSortDescriptor(key: NSMetadataItemFSContentChangeDateKey, ascending: false)]
        searching = true
        observer = NotificationCenter.default.addObserver(forName: .NSMetadataQueryDidFinishGathering,
                                                          object: m, queue: .main) { [weak self] _ in
            Task { @MainActor in
                guard let self else { return }
                m.disableUpdates()
                var out: [FoundFile] = []
                for i in 0..<min(m.resultCount, 80) {
                    guard let item = m.result(at: i) as? NSMetadataItem,
                          let p = item.value(forAttribute: NSMetadataItemPathKey) as? String,
                          !p.contains("/Library/"), !p.contains("/."), !p.contains("/node_modules/") else { continue }
                    out.append(FoundFile(path: p, modified: item.value(forAttribute: NSMetadataItemFSContentChangeDateKey) as? Date))
                }
                self.results = out
                self.searching = false
                m.stop()
            }
        }
        mdq = m
        m.start()
    }
}

struct FilesView: View {
    @ObservedObject var store: FileSearch
    @ObservedObject var backend: Backend
    @ObservedObject var hub: Hub

    var body: some View {
        VStack(spacing: 0) {
            ModuleHeader(title: "Find files", subtitle: "Spotlight — names\(store.contents ? " and contents" : "")") {
                if store.searching { ProgressView().controlSize(.small) }
            }
            HStack(spacing: 6) {
                SearchField(text: $store.query, placeholder: "Search your Mac…", onSubmit: store.run)
                Chip(label: "Contents", icon: "text.magnifyingglass", selected: store.contents) {
                    store.contents.toggle(); store.run()
                }
                Menu(store.scope) {
                    ForEach(["Home", "Documents", "Downloads", "Desktop"], id: \.self) { s in
                        Button(s) { store.scope = s; store.run() }
                    }
                }
                .menuStyle(.button).buttonStyle(.plain).fixedSize()
                .font(.system(size: 11)).foregroundStyle(Theme.secondary)
            }
            .padding(.horizontal, 18).padding(.bottom, 8)
            .onChange(of: store.query) { _ in
                NSObject.cancelPreviousPerformRequests(withTarget: store)
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.35) { store.run() }
            }
            if store.results.isEmpty {
                EmptyHint(icon: store.notice == nil ? "doc.text.magnifyingglass" : "lock.shield",
                          text: store.notice ?? (store.query.count < 2 ? "Type to search file names and what's inside them.\nOr just ask Ledge: “find my offer letter PDF”."
                                                      : (store.searching ? "Searching…" : "Nothing found.")))
            } else {
                ScrollView {
                    LazyVStack(spacing: 4) {
                        ForEach(store.results) { f in fileRow(f) }
                    }
                    .padding(.horizontal, 14).padding(.bottom, 12)
                }
            }
        }
    }

    private func fileRow(_ f: FoundFile) -> some View {
        HStack(spacing: 10) {
            appIcon(forPath: f.path, size: 26).resizable().frame(width: 26, height: 26)
            VStack(alignment: .leading, spacing: 2) {
                Text((f.path as NSString).lastPathComponent).font(.system(size: 12, weight: .medium)).lineLimit(1)
                Text(f.path.replacingOccurrences(of: NSHomeDirectory(), with: "~"))
                    .font(.system(size: 10, design: .monospaced)).foregroundStyle(Theme.tertiary)
                    .lineLimit(1).truncationMode(.middle)
            }
            Spacer(minLength: 0)
            if let m = f.modified {
                Text(relativeTime(m)).font(.system(size: 10)).foregroundStyle(Theme.tertiary)
            }
        }
        .padding(7)
        .background(RoundedRectangle(cornerRadius: 9).fill(.white.opacity(0.035)))
        .contentShape(Rectangle())
        .onTapGesture(count: 2) { NSWorkspace.shared.open(URL(fileURLWithPath: f.path)) }
        .onDrag { NSItemProvider(contentsOf: URL(fileURLWithPath: f.path)) ?? NSItemProvider() }
        .contextMenu {
            Button("Open") { NSWorkspace.shared.open(URL(fileURLWithPath: f.path)) }
            Button("Show in Finder") { NSWorkspace.shared.activateFileViewerSelecting([URL(fileURLWithPath: f.path)]) }
            Button("Ask Ledge about it") {
                backend.attach(Attachment(kind: .file, value: f.path)); hub.module = .chat
            }
            Button("Keep on Shelf") { hub.shelf.add([URL(fileURLWithPath: f.path)]) }
            Button("Copy path") { copyToClipboard(f.path) }
        }
    }
}
